Add initial getting started guide
Kuadrant/kcp-glbc pull request #286
Opened 2022-07-20 16:24 UTC by joaedwar

Closes #266 

## Description of Changes

* Add initial content for GLBC's installation (and verification)  and an overview on kcp
* Initial content for how to use the GLBC to provide ingress in a multi-cluster ingress scenario (kind clusters are fine initially)

## Remaining Work 

The following changes still need to be completed:

- [ ] Add tutorial steps for multi-cluster ingress scenario
- [ ] Update, add, and explain architecture diagram

2022-08-11 11:57 UTC, david-martin requested changes
I've followed through while on the latest `main` branch.
I got to the end OK, with some cmd changes which I've left suggestions for.
I've also left some minor technical corrections, clarifications & suggestions for simplifying the upkeep of this tutorial.

2022-08-11 11:57 UTC, david-martin commented on docs/getting_started/tutorial.md
> +* Downloads KCP 0.6.0
```suggestion
* Downloads KCP at the latest version integrated with glbc
```
The KCP version will change frequently.

2022-08-11 11:57 UTC, david-martin commented on docs/getting_started/tutorial.md
> +Run Option 1 (Local):
This has changed on main now
https://github.com/Kuadrant/kcp-glbc/blob/main/utils/local-setup.sh#L226-L230
I think this can be removed?
See also next comment.

2022-08-11 11:57 UTC, david-martin commented on docs/getting_started/tutorial.md
> +(export $(cat ./config/deploy/local/controller-config.env | xargs) && export $(cat ./config/deploy/local/aws-credentials.env | xargs) && ./bin/kcp-glbc --kubeconfig .kcp/admin.kubeconfig)
Given the changes mentioned above,
I think this is the cmd you'd need here?
```
(export $(cat ./config/deploy/local/controller-config.env | xargs) && export $(cat ./config/deploy/local/aws-credentials.env | xargs) && KUBECONFIG=./tmp/kcp.kubeconfig ./bin/kcp-glbc)
```

2022-08-11 11:57 UTC, david-martin commented on docs/getting_started/tutorial.md
> +1. Verify that the ingress was created after deploying the sample service:
```suggestion
1. In a new terminal, verify that the ingress was created after deploying the sample service:
```

2022-08-11 11:57 UTC, david-martin commented on docs/getting_started/tutorial.md
> +kubectl get ingress
```suggestion
kubectl get ingress

NAME                AGE
ingress-nondomain   81s
```

2022-08-11 11:57 UTC, david-martin commented on docs/getting_started/tutorial.md
> +kubectl get ingress
Include expected output?

2022-08-11 11:57 UTC, david-martin commented on docs/getting_started/tutorial.md
> +<b>Note: This version of the tutorial works with KCP 0.6.0.</b>
```suggestion
```
Can remove as kcp 0.6 is on main

2022-08-11 11:57 UTC, david-martin commented on docs/getting_started/tutorial.md
> +For that reason we can also observe another annotation named "*finalizers.workload.kcp.dev/kcp-cluster-1: kuadrant.dev/glbc-migration*" which remains there because GLBC is saying to KCP "Don't get ri
```suggestion
For that reason we can also observe another annotation named "*finalizers.workload.kcp.dev/kcp-cluster-1: kuadrant.dev/glbc-migration*" which remains there because GLBC is saying to KCP "Don't get rid of this yet, as we're waiting for it to come up to another cluster before you remove it from *kcp-cluster-1*" Once it has completely migrated and sufficient time has been allowed for DNS propagation, the finalizer for *kcp-cluster-1* will no longer be there and the workload will be deleted from *kcp-cluster-1*.
A DNS propagation time of the TTL (usually 60 seconds) * 2 is allowed for.
```

2022-08-12 12:05 UTC, ChristianZaccaria commented on docs/getting_started/overview.md
> +Kube-like Control Plane (KCP) is a prototype of a multi-tentant Kubernetes control plane for workloads on many clusters.
That's a very nice catch, I actually didn't know that. Thanks David !

@joaedwar can you check the suggested changes and recommendations by David related to the overview document? I'll check the ones for the tutorial document. Perhaps afterwards we could merge what we have and make further changes as needed.

2022-08-12 13:01 UTC, ChristianZaccaria commented on docs/getting_started/tutorial.md
> +(export $(cat ./config/deploy/local/controller-config.env | xargs) && export $(cat ./config/deploy/local/aws-credentials.env | xargs) && ./bin/kcp-glbc --kubeconfig .kcp/admin.kubeconfig)
Yes, I see what you mean. You're absolutely right. I just tested it myself as well and works perfectly.

2022-08-18 09:37 UTC, jasonmadigan requested changes

2022-08-18 09:53 UTC, ChristianZaccaria commented on docs/getting_started/tutorial.md
> +- Install Go `1.17` or higher. This is the version used in KCP-GLBC as indicated in the [`go.mod`](https://github.com/Kuadrant/kcp-glbc/blob/main/go.mod) file.
You're absolutely right, thanks Jason

2022-08-18 10:00 UTC, ChristianZaccaria commented on docs/getting_started/tutorial.md
> +* Deploys three Kubernetes `1.22` clusters locally using kind
Yes good idea! I'll include that link.

 What do you mean by `s/KCP/kcp/g`?

2022-08-18 10:37 UTC, ChristianZaccaria commented on docs/getting_started/tutorial.md
> +   ![Screenshot from 2022-07-28 12-43-56](https://user-images.githubusercontent.com/73656840/181609374-b0d2c81f-0d46-4816-b53e-05514fa382c2.png)
I think that those fields are already generated and would just need to change a few of them. But yes copy/pasting would be much quicker. I just added it there, thanks Jason

2022-08-18 14:09 UTC, jasonmadigan commented on docs/getting_started/tutorial.md
> +* Deploys three Kubernetes `1.22` clusters locally using kind
I'd replace refs to `KCP` to instead use `kcp` (since that's what kcp call themselves)

2022-08-19 08:24 UTC, ChristianZaccaria commented on docs/getting_started/tutorial.md
> +* Deploys three Kubernetes `1.22` clusters locally using kind
Oh I get you of course, you're right

2022-08-19 14:17 UTC, ChristianZaccaria commented on docs/getting_started/tutorial.md
> +make local-setup
Excellent one! That's now included in the document. Thank you :+1:

2022-08-23 10:30 UTC, maleck13 commented
@jasonmadigan ok to cast your eye over this again and approve if you are happy with the changes?

2022-08-23 13:16 UTC, jasonmadigan requested changes
one small change - other than that looks in good shape to merge!

2022-08-23 13:28 UTC, ChristianZaccaria commented on docs/getting_started/overview.md
> +KCP is a prototype of a multi-tentant Kubernetes control plane for workloads on many clusters.
That's fixed now, thanks Jason :+1:

2022-08-23 14:05 UTC, jasonmadigan approved these changes

2022-08-23 14:06 UTC, jasonmadigan commented
Looks good - if you'd like to squash before merge, let me know.

2022-08-23 15:12 UTC, merged