Tls certificate alerts
Kuadrant/kcp-glbc pull request #290
Opened 2022-07-21 13:01 UTC by ChristianZaccaria

Closes #191 

**Please note: PR #285 must be merged first before merging this PR**

## Description of Changes
I created two alerts:

- Triggered when calls to the TLS Provider (Let's Encrypt) have excessive errors or disconnections:
  - The expression used for this divides the total errors by the total requests, giving us the error rate in percentage. At the moment, it is triggered when the error rate is higher than 1%.
  - I created the appropriate unit tests to verify that it is working. In the test, there is an error rate of 2% which will be expected for the alert to be triggered.

- Triggered when calls to the TLS Provider (Let's Encrypt) have high latency.
  - The expression used for this divides the duration time in seconds by the total counted requests, giving us the latency rate. At the moment, it is triggered when the latency per request is greater than 0.5 seconds.
  - I created the unit test. There is a 0.6 seconds latency of which will be expected for the alert to be triggered.

I added documentation to each alert for SRE in case the alert is firing. This document provides more information on the alert and the prerequisites to solve the issue. Also, ideas on how it can be solved and how to troubleshoot it are also included.

2022-07-25 15:15 UTC, david-martin requested changes
Left a couple comments looking for input from others.
I've created a follow up, similar to the DNS alerts follow up, for future consideration #295

2022-07-25 15:15 UTC, david-martin commented on config/observability/kubernetes/monitoring_resources/rules-glbc-prometheusrule.yaml
> +          expr: "sum(rate(glbc_tls_certificate_issuance_duration_seconds_sum[5m])) / sum(rate(glbc_tls_certificate_issuance_duration_seconds_count[5m])) > 0.5"
0.5 seconds is too low a value.
I believe we should be looking in the region of minutes rather than milliseconds (waiting for a certificate request to be signed).
It's worth finding some official docs from the cert provider on what the expected turnaround is.

@astefanutti I'd appreciate your input on this as well since I think you added the metric initally?

2022-07-25 15:15 UTC, david-martin commented on docs/observability/runbooks/HighTLSProviderErrorRate.adoc
> +
@maleck13 Do you think we should include some cert-manager debugging steps here?
There's probably a larger question to be answered though around cert-manager if it's part of the same deployment stack as glbc, and we'd need to add some alerts for cert-manager.

2022-07-25 15:28 UTC, maleck13 commented on docs/observability/runbooks/HighTLSProviderErrorRate.adoc
> +
I think at a min we can add to view logs from cert-manager also potentially take a look at the related CertificateRequest resource https://cert-manager.io/docs/faq/troubleshooting/#2-checking-the-certificaterequest

alerts for cert manager would be outside of this PR  but I think it is likely we will also need them https://cert-manager.io/docs/usage/prometheus-metrics/

2022-07-25 15:52 UTC, david-martin commented on docs/observability/runbooks/HighTLSProviderErrorRate.adoc
> +
That sounds reasonable.
I've created an issue for the latter #296.

> I think at a min we can add to view logs from cert-manager also potentially take a look at the related CertificateRequest resource https://cert-manager.io/docs/faq/troubleshooting/#2-checking-the-certificaterequest

@ChristianZaccaria can you add something to this effect?

2022-08-01 11:58 UTC, ChristianZaccaria commented on docs/observability/runbooks/HighTLSProviderErrorRate.adoc
> +
Absolutely, that is perfect. I just added the commands to access the logs from cert-manager and added another link to for Support in the Let's Encrypt community if needed. For what I could see in questions asked by other people, they usually take less than a day to answer back.

2022-08-08 10:27 UTC, maleck13 commented
@ChristianZaccaria @david-martin wondering what the status on this one is? Are we hoping to merge it soon

2022-08-09 08:29 UTC, david-martin commented on docs/observability/runbooks/HighTLSProviderLatencyAlert.adoc
> +. Let's Encrypt does not provide support via email. Support questions are answered in their https://community.letsencrypt.org/[community forums].
@ChristianZaccaria Might be good to add checking of https://letsencrypt.status.io/

2022-08-09 08:32 UTC, david-martin commented on config/observability/kubernetes/monitoring_resources/rules-glbc-prometheusrule.yaml
> +          expr: "sum(rate(glbc_tls_certificate_issuance_duration_seconds_sum[5m])) / sum(rate(glbc_tls_certificate_issuance_duration_seconds_count[5m])) > 0.5"
@maleck13 or @astefanutti 
I think this is the only open item on this PR.
Any thoughts on a reasonable starting threshold for average cert issue time to alert on?
Both myself & @ChristianZaccaria found it difficult to get concrete published data from letsencrypt on what level of service to expect. 
I'd also suspect le stage is different than le prod. 

To help answer this, consider what we would do if it fires.
Either it's our problem (misconfiguration etc..) or it's their problem.
If it's a problem on their end, our only course of action seems to be the [community forums](https://community.letsencrypt.org/t/welcome-to-lets-encrypt-community-support/8)

2022-08-09 10:35 UTC, maleck13 commented on config/observability/kubernetes/monitoring_resources/rules-glbc-prometheusrule.yaml
> +          expr: "sum(rate(glbc_tls_certificate_issuance_duration_seconds_sum[5m])) / sum(rate(glbc_tls_certificate_issuance_duration_seconds_count[5m])) > 0.5"
We could have a second issuer resource also in which case the course of action would be to switch to that one. It doesn't really help with renewals as they would need to go through the same provider (not an issue as certmanager will handle this) but also renewals are done well ahead of time. 
As this is part of is an ingress ready, I would also say that is has to be less than any target SLO?

2022-08-09 11:03 UTC, ChristianZaccaria commented on docs/observability/runbooks/HighTLSProviderLatencyAlert.adoc
> +. Let's Encrypt does not provide support via email. Support questions are answered in their https://community.letsencrypt.org/[community forums].
Nice one, I just added it there to both TLS alert runbooks.

2022-08-11 12:00 UTC, david-martin commented on config/observability/kubernetes/monitoring_resources/rules-glbc-prometheusrule.yaml
> +          expr: "sum(rate(glbc_tls_certificate_issuance_duration_seconds_sum[5m])) / sum(rate(glbc_tls_certificate_issuance_duration_seconds_count[5m])) > 0.5"
> As this is part of is an ingress ready, I would also say that is has to be less than any target SLO?

Agreed. 
@ChristianZaccaria Let's start with 2 minutes as the threshold here.
We can tweak that based on observances in future and outcomes of load testing.
We can merge after this change.

2022-08-12 11:30 UTC, ChristianZaccaria commented on config/observability/kubernetes/monitoring_resources/rules-glbc-prometheusrule.yaml
> +          expr: "sum(rate(glbc_tls_certificate_issuance_duration_seconds_sum[5m])) / sum(rate(glbc_tls_certificate_issuance_duration_seconds_count[5m])) > 0.5"
I changed the threshold to 2 minutes (120 seconds), made the changes to each file including the runbook and unit tests @david-martin

2022-08-15 08:25 UTC, merged