Update to KCP 0.6
Kuadrant/kcp-glbc pull request #308
Opened 2022-07-28 16:05 UTC by mikenairn

Closes #265 

## Description of Changes
Update to KCP 0.6 (release-0.6)

Replaces https://github.com/Kuadrant/kcp-glbc/pull/289 which has a strange commit history.

2022-07-29 15:34 UTC, david-martin requested changes
Some comments above.

Also, the deploy-observability script errored out with this:
```
Error from server (NotFound): error when creating "config/observability/kubernetes/monitoring_resources/podmonitor-kcp-glbc-controller-manager.yaml": namespaces "kcp89b5fd4ba9405ee7b18d0da859ce7420d36926bac4a97e01af5c244a" not found
```
The namespace was preivously hardcoded in the script by the look of it.
Perhaps with the upgrade to kcp 0.6 that's no longer the case?

2022-07-29 15:34 UTC, david-martin commented on pkg/reconciler/ingress/dns_reconciler.go
> +		if metadata.HasAnnotation(ingress, workloadMigration.WorkloadDeletingAnnotation+annotationParts[1]) {
Could this give an `index out of range` on `annotationParts[1]` since the change above will `continue` when there's less than 2 parts to the annotation?

2022-07-29 15:34 UTC, david-martin commented on pkg/reconciler/ingress/dns_reconciler.go
> +		clusterName := annotationParts[1]
same as above comment for `index out of range`?

2022-07-29 15:34 UTC, david-martin commented on pkg/reconciler/ingress/dns_reconciler.go
>  // targetsFromIngressStatus returns a map of all the IPs associated with a single ingress(cluster)
typo or copy/paste mistake on the comment for the func? targetsFromIngressStatus vs targetsFromIngress

2022-07-29 15:34 UTC, david-martin commented on pkg/reconciler/ingress/dns_reconciler.go
> +			targets[host] = append(targets[host], ips...)
Wondering if I'm missing something obvious here.
Here all the `statusTargets` are added to the `targets` map.
Below, a check is done for `if len(targets) == 0 && len(deletingTargets) > 0`
Will it ever be possible for there to be more than 0 `deletingTargets` and no `targets`, since even the deleting targets are always appended to `targets`?

2022-07-29 18:28 UTC, mikenairn commented
> Also, the deploy-observability script errored out with this:
> 
> ```
> Error from server (NotFound): error when creating "config/observability/kubernetes/monitoring_resources/podmonitor-kcp-glbc-controller-manager.yaml": namespaces "kcp89b5fd4ba9405ee7b18d0da859ce7420d36926bac4a97e01af5c244a" not found
> ```
> 
> The namespace was previously hardcoded in the script by the look of it. Does it make sense to update it to the namespace name there now `kcp-2at5p6hmqk1o` or will that be different each time

I fixed this in my [PR](https://github.com/Kuadrant/kcp-glbc/pull/303/files#diff-89019f25d9c0356755de9e4b218b898ba3cbb3f9415d6edc92684ba1f1ce4ad6) , but since this is the one introducing the error, I'll roll it into this one.

2022-08-02 09:02 UTC, mikenairn commented on pkg/reconciler/ingress/dns_reconciler.go
> +			targets[host] = append(targets[host], ips...)
It looks like it continues before adding any deleting targets to `targets` https://github.com/Kuadrant/kcp-glbc/pull/308/commits/fe79ba8ad76347fffc1785d0932cb8bf626a6890#diff-fe02380a729e1ed7165d9dbd232b88175ffc9ab52454a4ec3e60cbc243c6a606R242. I guess the logic here is if we have at least one non deleting target we can remove all deleting targets from the record, until then we return any deleting targets.

2022-08-02 09:06 UTC, mikenairn commented on pkg/reconciler/ingress/dns_reconciler.go
> +		if metadata.HasAnnotation(ingress, workloadMigration.WorkloadDeletingAnnotation+annotationParts[1]) {
If it continues on less than length 2, why would it get this far to get an index out of range on the second element in the array?

2022-08-02 09:34 UTC, david-martin commented on pkg/reconciler/ingress/dns_reconciler.go
> +		if metadata.HasAnnotation(ingress, workloadMigration.WorkloadDeletingAnnotation+annotationParts[1]) {
You're right. 
I think we can resolve this thread

2022-08-02 09:36 UTC, david-martin commented on pkg/reconciler/ingress/dns_reconciler.go
> +			targets[host] = append(targets[host], ips...)
You're right. 
That makes sense, given the outer for loop.

2022-08-02 13:48 UTC, david-martin approved these changes
Thanks for addressing the comments and questions

2022-08-03 07:51 UTC, mikenairn commented
There were a couple of issues observed during testing https://github.com/Kuadrant/kcp-glbc/issues/312, https://github.com/Kuadrant/kcp-glbc/issues/309, but nothing that looks to be directly caused by this update. Unsure why the metrics test fails consistently on this branch and not on main (0.5.0), but the same problem does exist there. This looks good to merge now, but those bugs should be looked into as a priority.

2022-08-03 07:52 UTC, merged