domain verification without webhooks
Kuadrant/kcp-glbc pull request #323
Opened 2022-08-15 08:54 UTC by philbrookes

Related to #80 

## Description of Changes
Implement domain verification.

## Remaining Work 
Implement webhooks

## Release and Testing
Create local-setup, apply the domain verification sample yaml.

2022-08-15 14:38 UTC, maleck13 commented on config/kcp/glbc-cluster-role.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
I am not sure we need this anymore?

2022-08-16 13:55 UTC, maleck13 commented
What is the best way to verify this locally?

2022-08-16 14:43 UTC, philbrookes commented
> What is the best way to verify this locally?

I've updated the description with steps.

2022-08-23 08:16 UTC, maleck13 reviewed
Few comments. Logic is much simpler now. I feel this work really needs an e2e test and also more attention paid to the tls section. Going to test it locally, but I think we lose the tls section for the custom domain?

2022-08-23 08:16 UTC, maleck13 commented on samples/domainverification/second-host.yaml
> +kind: Ingress
should we have a sample with tls?

2022-08-23 08:17 UTC, maleck13 commented on pkg/reconciler/ingress/host_reconciler.go
> +			hosts = append(hosts, rule.Host)
should it be renamed unverifiedHosts?

2022-08-23 08:22 UTC, maleck13 requested changes
address comments and test tls section. Add an issue to follow up with a proper e2e test

2022-08-23 08:43 UTC, philbrookes commented on pkg/reconciler/ingress/host_reconciler.go
> +		ingress.Annotations[PendingCustomHostsAnnotation] = string(newAnnotation)
I try to avoid returning "success" (i.e. no error) from multiple places, I think it can make the function hard to reason about

2022-08-23 10:17 UTC, maleck13 commented on pkg/net/hostresolv.go
> +	NoSuchHost = errors.New("No such host")
nit. Make var package private

2022-08-23 10:21 UTC, maleck13 commented on pkg/reconciler/domainverification/reconciler.go
> +	//consider moving to mutating webhook that will create this resource
prob can remove

2022-08-23 10:24 UTC, maleck13 commented on pkg/reconciler/ingress/controller.go
> +	ingressList, err := c.kubeClient.Cluster(logicalcluster.From(dv)).NetworkingV1().Ingresses("").List(context.TODO(), metav1.ListOptions{})
hmm this is also not ideal I now see as we have no context to use here. Wonder is it possible to get a lister that is scoped to the logical cluster?

2022-08-23 10:25 UTC, maleck13 commented on pkg/reconciler/ingress/host_reconciler.go
> +func hostMatches(host, domain string) bool {
do we use this? I am not seeing it used

2022-08-23 10:28 UTC, maleck13 requested changes
I think I spotted an unused function. Other than the tls and the unused function, looks good

2022-08-23 10:38 UTC, philbrookes commented on pkg/reconciler/ingress/host_reconciler.go
> +func hostMatches(host, domain string) bool {
Yes, it's called from the `ingressesFromDomainVerification` function.

2022-08-23 10:39 UTC, philbrookes commented
> I think I spotted an unused function. Other than the tls and the unused function, looks good

Cheers, still looking into the TLS. The unused function is used.

2022-08-23 10:46 UTC, maleck13 commented on pkg/reconciler/ingress/host_reconciler.go
> +func hostMatches(host, domain string) bool {
should this be used by the findDomainVerification? they seem to duplicate logic

2022-08-23 14:46 UTC, philbrookes commented on pkg/reconciler/ingress/host_reconciler.go
> +func hostMatches(host, domain string) bool {
rejigged this now.

2022-08-24 07:45 UTC, philbrookes commented on pkg/reconciler/ingress/controller.go
> +	ingressList, err := c.kubeClient.Cluster(logicalcluster.From(dv)).NetworkingV1().Ingresses("").List(context.TODO(), metav1.ListOptions{})
oh, it is already, the informer factory is scoped to the workspace here: https://github.com/Kuadrant/kcp-glbc/blob/main/cmd/kcp-glbc/main.go#L151

2022-08-24 08:39 UTC, mikenairn commented on cmd/kcp-glbc/main.go
> +	"github.com/kuadrant/kcp-glbc/pkg/reconciler/domainverification"
These should be moved down to be with the rest of the  kcp-glbc imports

2022-08-24 08:41 UTC, mikenairn commented on pkg/apis/kuadrant/v1/types.go
>  	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
consider grouping these, we do it most other places

2022-08-24 08:45 UTC, mikenairn commented on pkg/reconciler/domainverification/controller.go
> +	basereconcile "github.com/kuadrant/kcp-glbc/pkg/reconciler"
Is there a reason this is here, and not with the rest of the local imports? local imports also should be last should they not?

2022-08-24 08:51 UTC, mikenairn commented on pkg/reconciler/domainverification/reconciler.go
> +)
import grouping

2022-08-24 08:51 UTC, mikenairn commented on pkg/reconciler/ingress/controller.go
> +	"strings"
import grouping

2022-08-24 08:52 UTC, mikenairn commented on pkg/reconciler/ingress/host_reconciler.go
>  	networkingv1 "k8s.io/api/networking/v1"
import grouping

2022-08-24 08:52 UTC, mikenairn commented on pkg/reconciler/ingress/ingress_reconciler.go
>  	"strings"
import grouping

2022-08-24 14:57 UTC, maleck13 commented on pkg/reconciler/ingress/controller.go
> +	ingressList, err := c.kubeClient.Cluster(logicalcluster.From(dv)).NetworkingV1().Ingresses("").List(context.TODO(), metav1.ListOptions{})
right but that it likely set to * so when we list we will list all ingresses

2022-08-26 08:06 UTC, maleck13 commented on pkg/reconciler/dns/controller.go
> +		_, err := c.dnsRecordClient.Cluster(logicalcluster.From(current)).KuadrantV1().DNSRecords(current.Namespace).UpdateStatus(ctx, current, metav1.UpdateOptions{})
this returns the dnsrecord object. I would have thought it is the udpated one with the new resource version?

2022-08-26 08:28 UTC, philbrookes commented on pkg/reconciler/dns/controller.go
> +		_, err := c.dnsRecordClient.Cluster(logicalcluster.From(current)).KuadrantV1().DNSRecords(current.Namespace).UpdateStatus(ctx, current, metav1.UpdateOptions{})
oh nice, that's a lot neater

2022-08-26 08:29 UTC, maleck13 commented on pkg/reconciler/domainverification/controller.go
> +		_, err := c.domainVerificationClient.Cluster(logicalcluster.From(current)).KuadrantV1().DomainVerifications().UpdateStatus(ctx, current, metav1.UpdateOptions{})
same here I don't think we need to do a get just need to use the object returned?

2022-08-26 08:30 UTC, philbrookes commented on pkg/reconciler/domainverification/controller.go
> +		_, err := c.domainVerificationClient.Cluster(logicalcluster.From(current)).KuadrantV1().DomainVerifications().UpdateStatus(ctx, current, metav1.UpdateOptions{})
yep, will test this and update the PR

2022-08-26 08:33 UTC, maleck13 commented on pkg/reconciler/domainverification/reconciler.go
> +	//updateErr := dsr.updateStatus(ctx, dv)
remove?

2022-08-26 08:48 UTC, maleck13 commented on pkg/reconciler/domainverification/reconciler.go
> +func (c *Controller) updateStatus(ctx context.Context, dv *v1.DomainVerification) error {
This looks like it is unused now?

2022-08-26 08:49 UTC, maleck13 commented on pkg/reconciler/ingress/controller.go
> +			c.Logger.Info("domainverification update event")
prob can remove might be noisey?

2022-08-26 08:51 UTC, maleck13 commented on pkg/reconciler/ingress/controller.go
> +	c.dnsRecordInformerFactory.Kuadrant().V1().DomainVerifications().Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
this looks weird it says dnsRecordInformerFactory?

2022-08-26 08:59 UTC, philbrookes commented on pkg/reconciler/ingress/controller.go
> +	c.dnsRecordInformerFactory.Kuadrant().V1().DomainVerifications().Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
yeah, it's the Kuadrant client but it was named a bit strangely in this controller, I can rename it

2022-08-26 09:00 UTC, maleck13 commented on pkg/reconciler/ingress/controller.go
> +	ingressList, err := c.ingressLister.Ingresses("").List(labels.Everything())
Did you figure out what this does? Does it list everything in all workspaces?

2022-08-26 09:16 UTC, maleck13 commented on pkg/reconciler/ingress/host_reconciler.go
> +	dvs, err := r.kuadrantClient.Cluster(logicalcluster.From(ingress)).KuadrantV1().DomainVerifications().List(ctx, metav1.ListOptions{})
shouldn't this follow the same kind of pattern as the others so it can be mocked in tests if needed?

2022-08-26 09:31 UTC, philbrookes commented on pkg/reconciler/ingress/host_reconciler.go
> +	dvs, err := r.kuadrantClient.Cluster(logicalcluster.From(ingress)).KuadrantV1().DomainVerifications().List(ctx, metav1.ListOptions{})
yeah, didn't consider that, as the client seemed to be available, I'll refactor this now.

2022-08-26 10:21 UTC, maleck13 reviewed
happy with the changes now. Def need an e2e test for this though can we link in that issue?
Going to verify locally and then will approve

2022-08-26 10:44 UTC, philbrookes commented
https://github.com/Kuadrant/kcp-glbc/issues/344

2022-08-26 13:30 UTC, merged