Use upstream certmanager helm chart
Kuadrant/kcp-glbc pull request #416
Opened 2022-09-20 21:24 UTC by roivaz

Closes #367

## Description of Changes

* Removes the locally checked cert-manager resources
* Enables use of helm with kustomize to use the upstream cert-manager helm chart, with the following modifications:
  * The cainjector component of cert-manager is disabled. When it's installed in kcp it fails because the APIService API is not present
  * The webhook component is disabled because it is exposed through a Service and so far only external urls are supported for webhooks in kcp. As the helm chart does not have an option to disable the webhook, I have set the number of webhook replicas to 0 and removed the rules field in the ValidatingWebhookConfiguration and MutatingWebhookConfiguration resources to avoid cert-manager APIs from being intercepted and sent to the webhook.

## Remaining Work 

N/A

## Release and Testing

I have tested this by using:

```
❯ make local-setup
[...]

❯ export KUBECONFIG=.kcp/admin.kubeconfig
❯ cat <<'EOF' | kubectl apply -f -
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-crt
  namespace: kcp-glbc
spec:
  secretName: test-crt-secret
  dnsNames:
  - example.com
  - foo.example.com
  issuerRef:
    name: glbc-ca
EOF
❯ k -n kcp-glbc get certificate test-crt -ojsonpath='{.status.conditions}'
[{"lastTransitionTime":"2022-09-20T21:12:02Z","message":"Certificate is up to date and has not expired","observedGeneration":1,"reason":"Ready","status":"True","type":"Ready"}]

## Dependencies

N/A

2022-09-21 09:27 UTC, david-martin requested changes
Tried out locally and works as expected.
1 small thing (mentioned offline already):
- helm may not be installed (and may be at an unexpected version if it is installed). We could instruct to install globally, or I think it better to install it locally to the `./bin` folder similar to other binaries and then pass the `--helm-command` flag to kustomize

2022-09-22 14:31 UTC, roivaz commented
Added local installation of helm with ec42063. It has worked for me, but would be nice if you could double check :)

2022-09-23 10:40 UTC, roivaz commented
@david-martin I have fixed also the e2e workflow, which was failing due to the helm binary missing

2022-09-23 15:25 UTC, david-martin commented on Makefile
> +	curl -s $(HELM_INSTALL_SCRIPT) | HELM_INSTALL_DIR=$(LOCALBIN) bash -s -- --no-sudo --version $(HELM_VERSION)
```suggestion
	curl -s $(HELM_INSTALL_SCRIPT) | HELM_INSTALL_DIR=$(LOCALBIN) PATH=$$PATH:$$HELM_INSTALL_DIR bash -s -- --no-sudo --version $(HELM_VERSION)
```

2022-09-23 15:26 UTC, david-martin commented on Makefile
> +	curl -s $(HELM_INSTALL_SCRIPT) | HELM_INSTALL_DIR=$(LOCALBIN) bash -s -- --no-sudo --version $(HELM_VERSION)
This will ensure it detects the local helm in cases where you don't have a global helm installed (the install script does a `command -v helm`)

2022-09-23 15:59 UTC, david-martin approved these changes

2022-09-23 15:59 UTC, merged